# Generated by Django 5.0.6 on 2024-07-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_subjects_subjectmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
